(head (list 1 2))
(tail (list 1 "hest"))
(+ (head (list 1 2)) (tail (list 2 1)))
(head (list (list a b) "hest" ))
(head (head (list (list a b) "hest" )))
(tail (list (list a b) "hest" ))
(head (list + -)) 