(head (list 1 2))
(tail (list 1 "hest"))
(+ (head (list 1 2)) (tail (list 2 1)))
(head (list (list a b) "hest" ))
(tail (list (list a b) "hest" ))
(head (list + -)) 
(eval (list + 1 2))
(list (head (list "hest")))
(eval (pprint(join (list +) (list 2 3))))
(define (x) (+ 1 2 y))
(define y 2)
(+ y y)